### PR TITLE
1020 041222 rebase on upstream

### PR DESCRIPTION
**Pull request by geissonator**

### CODE REVIEW

**Comment by geissonator** [comment]
Seems we're using upstream anyway. At some point though if we come back to this branch, we need to fix it.

**Comment by aahmed-2** [comment]
@rfrandse Do you think we can get this merged. I think we can ignore the merge conflicts and just with the rebase on to upstream?

**Comment by geissonator** [comment]
@aahmed-2 Is there a need to pull Telemetry downstream at this point? Right now we're just using upstream.

**Comment by aahmed-2** [comment]
Yes - we need to change a build option for Metric Report build limit from upstream from 25  to 18000 or so. @geissonator 

Sensors team on append limit:
"but 256 is laughably low"

HMC team:
"It looks like for AppendLimit one uses 17280 and the others 512."

I would rather get ahead on users using up to 20000 reading appends to make sure there are no bugs.

**Pull request merged**
